version: '3'
services:
  api:
    container_name: mockPizza-api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    container_name: mockPizza-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - /postgres-volume:/var/lib/postgresql/data
    

volumes:
  postgres-volume: